### ISSUE TITLE
deno do support top-level await

### ISSUE THREAD

**Issue by satishbabariya** [phil-r/q#1]
deno do support top-level await now, so there is no need to wrap `(async () => {})();`
ref: https://github.com/denoland/deno/issues/471

https://github.com/phil-r/q/blob/cf1eb6a8bd597839418ac2274f486db5debd891c/examples/async.ts#L3

**Comment by phil-r** [comment]
That's great! I tried it in REPL, but it doesn't work there, will update example ;)
